name: apart_hub
description: Apart-Hub app for connecting tenants and accommodation managers.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^6.4.1
  cupertino_icons: ^1.0.8
  firebase_auth: any
  firebase_core: any
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_maps_flutter: any
  http: any
  image_picker: any
  url_launcher: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
