services:
  - type: web
    name: smart-room-payos-backend
    runtime: node
    rootDir: functions
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PAYOS_CLIENT_ID
        sync: false
      - key: PAYOS_API_KEY
        sync: false
      - key: PAYOS_CHECKSUM_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_BASE64
        sync: false
