// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8RRjKtT6kbzPvOjM27NyVRyBlLRLa6YQ',
    appId: '1:537792897840:web:4b1aa27d8abf1207de1ef5',
    messagingSenderId: '537792897840',
    projectId: 'smart-room-iot-353c5',
    authDomain: 'smart-room-iot-353c5.firebaseapp.com',
    storageBucket: 'smart-room-iot-353c5.firebasestorage.app',
    measurementId: 'G-300XKPK98J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu1BLEFA3Snj7wK6m27Tb_-rzsGNJUVXg',
    appId: '1:537792897840:android:f68f18dc17329f2ade1ef5',
    messagingSenderId: '537792897840',
    projectId: 'smart-room-iot-353c5',
    storageBucket: 'smart-room-iot-353c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9oZfAnqa3j2bM-YI6jBMukyNWdcvbO_c',
    appId: '1:537792897840:ios:3cb0d8f27a6e5fc1de1ef5',
    messagingSenderId: '537792897840',
    projectId: 'smart-room-iot-353c5',
    storageBucket: 'smart-room-iot-353c5.firebasestorage.app',
    iosBundleId: 'com.example.smartRoomIotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9oZfAnqa3j2bM-YI6jBMukyNWdcvbO_c',
    appId: '1:537792897840:ios:3cb0d8f27a6e5fc1de1ef5',
    messagingSenderId: '537792897840',
    projectId: 'smart-room-iot-353c5',
    storageBucket: 'smart-room-iot-353c5.firebasestorage.app',
    iosBundleId: 'com.example.smartRoomIotApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8RRjKtT6kbzPvOjM27NyVRyBlLRLa6YQ',
    appId: '1:537792897840:web:437c0e1223b7cf0bde1ef5',
    messagingSenderId: '537792897840',
    projectId: 'smart-room-iot-353c5',
    authDomain: 'smart-room-iot-353c5.firebaseapp.com',
    storageBucket: 'smart-room-iot-353c5.firebasestorage.app',
    measurementId: 'G-0DL3JESGLF',
  );

}